In [1]:
import numpy as np

In [2]:
data=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',dtype=str )
data

array([['Age', 'Attrition', 'BusinessTravel', ...,
        'YearsInCurrentRole', 'YearsSinceLastPromotion',
        'YearsWithCurrManager'],
       ['41', 'Yes', 'Travel_Rarely', ..., '4', '0', '5'],
       ['49', 'No', 'Travel_Frequently', ..., '7', '1', '7'],
       ...,
       ['27', 'No', 'Travel_Rarely', ..., '2', '0', '3'],
       ['49', 'No', 'Travel_Frequently', ..., '6', '0', '8'],
       ['34', 'No', 'Travel_Rarely', ..., '3', '1', '2']],
      shape=(1471, 35), dtype='<U25')

In [23]:
headings=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',max_rows=1,dtype=str)
clean_head=np.char.replace(headings,'"','')
for index,colname in enumerate(clean_head):
    print(f"{index}={colname}")

0=Age
1=Attrition
2=BusinessTravel
3=DailyRate
4=Department
5=DistanceFromHome
6=Education
7=EducationField
8=EmployeeCount
9=EmployeeNumber
10=EnvironmentSatisfaction
11=Gender
12=HourlyRate
13=JobInvolvement
14=JobLevel
15=JobRole
16=JobSatisfaction
17=MaritalStatus
18=MonthlyIncome
19=MonthlyRate
20=NumCompaniesWorked
21=Over18
22=OverTime
23=PercentSalaryHike
24=PerformanceRating
25=RelationshipSatisfaction
26=StandardHours
27=StockOptionLevel
28=TotalWorkingYears
29=TrainingTimesLastYear
30=WorkLifeBalance
31=YearsAtCompany
32=YearsInCurrentRole
33=YearsSinceLastPromotion
34=YearsWithCurrManager


In [6]:
monthlyincome=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',usecols=18,skip_header=1,dtype=str)

In [7]:
monthlyincome

array(['5993', '5130', '2090', ..., '6142', '5390', '4404'],
      shape=(1470,), dtype='<U5')

In [8]:
clean_income=np.char.replace(monthlyincome,'"','')
income_to_int=clean_income.astype('int32')
income_to_int

array([5993, 5130, 2090, ..., 6142, 5390, 4404],
      shape=(1470,), dtype=int32)

In [9]:
np.mean(income_to_int)

np.float64(6502.931292517007)

In [10]:
np.std(income_to_int)

np.float64(4706.355164823003)

In [12]:
np.percentile(income_to_int,90)

np.float64(13775.600000000008)

In [15]:
greater_salary=income_to_int[income_to_int>13775]
np.size(greater_salary)

147

In [17]:
experience=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',dtype=str,skip_header=1,usecols=28)
clean_experience=np.char.replace(experience,'"','')
exp=clean_experience.astype('int32')
exp

array([ 8, 10,  7, ...,  6, 17,  6], shape=(1470,), dtype=int32)

In [18]:
np.corrcoef(exp,income_to_int)

array([[1.        , 0.77289325],
       [0.77289325, 1.        ]])

In [20]:
salary_hike=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',skip_header=1,usecols=23,dtype=str)
clean_salary=np.char.replace(salary_hike,'"','')
sal=clean_salary.astype('int32')
sal
np.argmax(sal)

np.int64(120)

In [25]:
yearsatcom=np.genfromtxt("employee_analysis_dataset/Employee_analysis.csv",delimiter=',',skip_header=1,dtype=str,usecols=31)
clean_years=np.char.replace(yearsatcom,'"','')
year_int=clean_years.astype('int32')
y=income_to_int[year_int>10]
print(np.mean(y))

10886.873983739837
