In [1]:
import numpy as np

In [5]:
data=np.genfromtxt("StudentsPerformance.csv",delimiter=',',skip_header=1,dtype=str)
header=np.genfromtxt("StudentsPerformance.csv",delimiter=',',max_rows=1,dtype=str)
clean_head=np.char.replace(header,'"','')
for index,colnames in enumerate(clean_head):
    print(f"{index}={colnames}")

0="gender"
1="race/ethnicity"
2="parental level of education"
3="lunch"
4="test preparation course"
5="math score"
6="reading score"
7="writing score"


In [3]:
data

array([['"female"', '"group B"', '"bachelor\'s degree"', ..., '"72"',
        '"72"', '"74"'],
       ['"female"', '"group C"', '"some college"', ..., '"69"', '"90"',
        '"88"'],
       ['"female"', '"group B"', '"master\'s degree"', ..., '"90"',
        '"95"', '"93"'],
       ...,
       ['"female"', '"group C"', '"high school"', ..., '"59"', '"71"',
        '"65"'],
       ['"female"', '"group D"', '"some college"', ..., '"68"', '"78"',
        '"77"'],
       ['"female"', '"group D"', '"some college"', ..., '"77"', '"86"',
        '"86"']], shape=(1000, 8), dtype='<U20')

In [4]:
math=np.genfromtxt("StudentsPerformance.csv",delimiter=',',skip_header=1,dtype=str,usecols=5)

In [5]:
math_clean=np.char.replace(math,'"','')
math_score=math_clean.astype('int32')

In [6]:
math_score

array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  40,  65,
        78,  50,  69,  88,  18,  46,  54,  66,  65,  44,  69,  74,  73,
        69,  67,  70,  62,  69,  63,  56,  40,  97,  81,  74,  50,  75,
        57,  55,  58,  53,  59,  50,  65,  55,  66,  57,  82,  53,  77,
        53,  88,  71,  33,  82,  52,  58,   0,  79,  39,  62,  69,  59,
        67,  45,  60,  61,  39,  58,  63,  41,  61,  49,  44,  30,  80,
        61,  62,  47,  49,  50,  72,  42,  73,  76,  71,  58,  73,  65,
        27,  71,  43,  79,  78,  65,  63,  58,  65,  79,  68,  85,  60,
        98,  58,  87,  66,  52,  70,  77,  62,  54,  51,  99,  84,  75,
        78,  51,  55,  79,  91,  88,  63,  83,  87,  72,  65,  82,  51,
        89,  53,  87,  75,  74,  58,  51,  70,  59,  71,  76,  59,  42,
        57,  88,  22,  88,  73,  68, 100,  62,  77,  59,  54,  62,  70,
        66,  60,  61,  66,  82,  75,  49,  52,  81,  96,  53,  58,  68,
        67,  72,  94,  79,  63,  43,  81,  46,  71,  52,  97,  6

In [7]:
np.mean(math_score)

np.float64(66.089)

In [8]:
reading=np.genfromtxt("StudentsPerformance.csv",delimiter=',',skip_header=1,dtype=str,usecols=6)
r_clean=np.char.replace(reading,'"','')
rscore=r_clean.astype("int32")
print(np.mean(rscore))

69.169


In [9]:
writing=np.genfromtxt("StudentsPerformance.csv",delimiter=',',skip_header=1,dtype=str,usecols=7)
w_clean=np.char.replace(writing,'"','')
wscore=w_clean.astype("int32")
print(np.mean(wscore))

68.054


In [10]:
np.corrcoef(rscore,wscore)

array([[1.        , 0.95459808],
       [0.95459808, 1.        ]])

In [11]:
write_weak=np.argmin(wscore)

In [12]:
write_weak

np.int64(59)

In [13]:
# highest std mean high risk,lower,less consistency in data
np.std(math_score)

np.float64(15.155496659628149)

In [14]:
np.std(rscore)

np.float64(14.592890015346516)

In [15]:
np.std(wscore)

np.float64(15.188057281956768)

In [16]:
total=math_score+rscore+wscore

In [17]:
total

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219,
       220, 161, 222, 263,  78, 134, 173, 198, 210, 151, 215, 225, 219,
       178, 211, 205, 207, 217, 189, 193, 120, 266, 241, 238, 173, 253,
       170, 170, 199, 176, 190, 160, 176, 182, 213, 207, 248, 156, 214,
       139, 241, 242, 117, 253, 156, 175,  27, 225, 112, 178, 220, 176,
       192, 119, 206, 175, 160, 194, 181, 140, 174, 139, 123,  78, 239,
       207, 198, 146, 139, 151, 199, 115, 235, 247, 216, 195, 241, 211,
        97, 221, 138, 257, 241, 193, 205, 187, 194, 213, 216, 265, 151,
       274, 197, 287, 193, 198, 206, 264, 166, 154, 163, 299, 235, 242,
       239, 175, 189, 260, 272, 274, 176, 236, 268, 207, 216, 238, 151,
       255, 130, 231, 240, 228, 161, 146, 181, 192, 201, 219, 185, 151,
       147, 239,  94, 247, 207, 224, 293, 198, 212, 195, 150, 190, 247,
       218, 180, 234, 192, 234, 248, 154, 154, 264, 296, 155, 212, 229,
       212, 219, 260, 246, 200, 148, 259, 158, 225, 184, 297, 20

In [18]:
top5=np.percentile(total,95)

In [19]:
top5

np.float64(270.04999999999995)

In [20]:
top_data=total[total>271]

In [21]:
top_data

array([278, 275, 274, 287, 299, 272, 274, 293, 296, 297, 277, 282, 275,
       275, 280, 282, 287, 289, 300, 273, 276, 275, 289, 278, 292, 279,
       274, 291, 275, 282, 296, 293, 297, 291, 276, 290, 281, 288, 293,
       300, 278, 275, 292, 300, 289, 280, 282], dtype=int32)